# Build NodeJS with Ubuntu
variables:
  imageName: 'ubuntu-latest'

pool:
  vmImage: $(imageName)
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install --verbose'

- script: |
    npm run build --if-present
    npm run test --if-present
  displayName: 'npm build and test'